### ISSUE TITLE
Turtle not being able to use upgraded block scanners

### ISSUE THREAD

**Issue by bragosmagos** [SwitchCraftCC/sc-goodies#68] opened 2024-05-21 09:26 UTC
Pretty much title. A turtle can equip a unupgraded block scanner in either of its hands, but if it's upgraded, it can't.

**Comment by Wojbie** [comment] 2024-05-21 09:30
This is a duplicate of https://github.com/SwitchCraftCC/Plethora-Fabric/issues/41 also this is posted under wrong mod.

**Closed as completed by Wojbie** 2024-05-21 09:30 UTC
